# Generated by Django 6.0.1 on 2026-01-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
