# Generated by Django 6.0.2 on 2026-02-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '* '), (2, '* * '), (3, '* * * '), (4, '* * * * '), (5, '* * * * * '), (6, '* * * * * * '), (7, '* * * * * * * '), (8, '* * * * * * * * '), (9, '* * * * * * * * * '), (10, '* * * * * * * * * * ')], default=4),
        ),
    ]
