# Generated by Django 6.0.1 on 2026-02-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
